name: Create a Release from a Tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
        # prerelease: true
        token: ${{secrets.GH_API_TOKEN}}